local P = require("noir.palette")

local function set(group, opts)
	vim.api.nvim_set_hl(0, group, opts)
end

local M = {}

function M.setup()
	local bg = P.bg
	local fg = P.fg

	-- UI
	set("Normal", { fg = fg, bg = bg })
	set("NormalFloat", { fg = fg, bg = P.alt_bg })
	set("FloatBorder", { fg = P.accent, bg = P.alt_bg })
	set("FloatTitle", { fg = P.fg, bg = P.alt_bg })
	set("MsgArea", { fg = fg, bg = bg })
	set("MsgSeparator", { fg = P.comment, bg = bg })
	set("Pmenu", { fg = fg, bg = P.visual })
	set("PmenuSel", { fg = P.bg, bg = P.accent })
	set("PmenuSbar", { bg = P.visual })
	set("PmenuThumb", { bg = P.comment })
	set("EndOfBuffer", { fg = bg })
	set("NonText", { fg = P.comment })
	set("Conceal", { fg = P.comment })
	set("Whitespace", { fg = P.visual })
	set("Cursor", { fg = P.bg, bg = P.fg })
	set("CursorLine", { bg = P.visual })
	set("CursorLineNr", { fg = fg })
	set("CursorColumn", { bg = P.alt_bg })
	set("LineNr", { fg = P.comment })
	set("SignColumn", { fg = P.comment, bg = bg })
	set("ColorColumn", { bg = P.alt_bg })
	set("FoldColumn", { fg = P.comment, bg = bg })
	set("Folded", { fg = P.comment, bg = P.alt_bg })
	set("StatusLine", { fg = fg, bg = P.bg })
	set("StatusLineNC", { fg = P.comment, bg = P.bg })
	set("StatusLineTerm", { fg = fg, bg = P.bg })
	set("StatusLineTermNC", { fg = P.comment, bg = P.bg })
	set("WinSeparator", { fg = P.alt_bg })
	set("VertSplit", { fg = P.alt_bg })
	set("TabLine", { fg = P.comment, bg = P.alt_bg })
	set("TabLineSel", { fg = P.bg, bg = P.accent })
	set("TabLineFill", { bg = P.alt_bg })
	set("Title", { fg = P.accent })
	set("Visual", { bg = P.visual })
	set("VisualNOS", { bg = P.visual })
	set("Search", { fg = P.bg, bg = P.accent })
	set("CurSearch", { fg = P.bg, bg = P.string })
	set("IncSearch", { fg = P.bg, bg = P.fg })
	set("MatchParen", { fg = P.bg, bg = P.comment })
	set("Question", { fg = P.accent })
	set("Directory", { fg = P.accent })
	set("SpecialKey", { fg = P.comment })
	set("Error", { fg = P.diag_red })
	set("ErrorMsg", { fg = P.diag_red, bg = bg })
	set("WarningMsg", { fg = P.diag_yellow })
	set("InfoMsg", { fg = P.accent })
	set("ModeMsg", { fg = fg })
	set("MoreMsg", { fg = P.accent })
	set("SpellBad", { fg = P.diag_red, sp = P.diag_red })
	set("SpellCap", { fg = P.diag_yellow, sp = P.diag_yellow })
	set("SpellLocal", { fg = P.diag_blue, sp = P.diag_blue })
	set("SpellRare", { fg = P.accent, sp = P.accent })
	set("QuickFixLine", { bg = P.visual })
	set("CursorLineSign", { fg = P.accent, bg = P.visual })

	-- Syntax
	set("Comment", { fg = P.comment, italic = true })
	set("Constant", { fg = P.constant })
	set("String", { fg = P.string })
	set("Character", { fg = P.string })
	set("Number", { fg = P.number })
	set("Float", { fg = P.number })
	set("Boolean", { fg = P.constant })
	set("Identifier", { fg = fg })
	set("Function", { fg = P.func })
	set("Statement", { fg = P.keyword })
	set("Conditional", { fg = P.keyword })
	set("Repeat", { fg = P.keyword })
	set("Label", { fg = P.keyword })
	set("Operator", { fg = P.operator })
	set("Keyword", { fg = P.keyword })
	set("Exception", { fg = P.keyword })
	set("PreProc", { fg = P.keyword })
	set("Include", { fg = P.keyword })
	set("Define", { fg = P.keyword })
	set("Macro", { fg = P.keyword })
	set("PreCondit", { fg = P.keyword })
	set("Type", { fg = P.type })
	set("StorageClass", { fg = P.keyword })
	set("Structure", { fg = P.type })
	set("Typedef", { fg = P.type })
	set("Special", { fg = P.accent })
	set("SpecialChar", { fg = P.accent })
	set("Tag", { fg = P.accent })
	set("Delimiter", { fg = P.operator })
	set("SpecialComment", { fg = P.comment, italic = true })
	set("Debug", { fg = P.accent })
	set("Underlined", { fg = P.accent, underline = true })
	set("Todo", { fg = P.bg, bg = P.string })
	set("Ignore", { fg = bg })

	-- Treesitter
	set("@comment", { fg = P.comment, italic = true })
	set("@error", { fg = P.diag_red })
	set("@string", { fg = P.string })
	set("@string.documentation", { fg = P.string })
	set("@string.regexp", { fg = P.string })
	set("@string.escape", { fg = P.accent })
	set("@character", { fg = P.string })
	set("@number", { fg = P.number })
	set("@float", { fg = P.number })
	set("@boolean", { fg = P.constant })
	set("@constant", { fg = P.constant })
	set("@constant.builtin", { fg = P.constant })
	set("@constant.macro", { fg = P.constant })
	set("@property", { fg = P.property })
	set("@symbol", { fg = P.accent })
	set("@identifier", { fg = fg })
	set("@variable", { fg = fg })
	set("@variable.builtin", { fg = P.constant })
	set("@variable.member", { fg = P.property })
	set("@variable.parameter", { fg = fg })
	set("@function", { fg = P.func })
	set("@function.call", { fg = P.func })
	set("@function.builtin", { fg = P.func })
	set("@function.macro", { fg = P.func })
	set("@function.method", { fg = P.func })
	set("@function.method.call", { fg = P.func })
	set("@function.documentation", { fg = P.comment })
	set("@keyword", { fg = P.keyword })
	set("@keyword.conditional", { fg = P.keyword })
	set("@keyword.repeat", { fg = P.keyword })
	set("@keyword.return", { fg = P.keyword })
	set("@keyword.operator", { fg = P.keyword })
	set("@keyword.import", { fg = P.keyword })
	set("@keyword.function", { fg = P.keyword })
	set("@keyword.type", { fg = P.keyword })
	set("@keyword.exception", { fg = P.keyword })
	set("@keyword.debug", { fg = P.keyword })
	set("@conditional", { fg = P.keyword })
	set("@repeat", { fg = P.keyword })
	set("@operator", { fg = P.operator })
	set("@type", { fg = P.type })
	set("@type.builtin", { fg = P.type })
	set("@type.definition", { fg = P.type })
	set("@type.qualifier", { fg = P.type })
	set("@storageclass", { fg = P.keyword })
	set("@storageclass.lifetime", { fg = P.keyword })
	set("@namespace", { fg = P.type })
	set("@parameter", { fg = fg })
	set("@field", { fg = P.property })
	set("@label", { fg = P.keyword })
	set("@tag", { fg = P.accent })
	set("@tag.delimiter", { fg = P.operator })
	set("@tag.attribute", { fg = P.property })
	set("@punctuation.delimiter", { fg = P.operator })
	set("@punctuation.bracket", { fg = P.operator })
	set("@punctuation.special", { fg = P.accent })
	set("@constructor", { fg = P.type })
	set("@attribute", { fg = P.property })
	set("@exception", { fg = P.keyword })
	set("@macro", { fg = P.keyword })
	set("@module", { fg = P.type })
	set("@preproc", { fg = P.keyword })
	set("@define", { fg = P.keyword })
	set("@include", { fg = P.keyword })
	set("@method", { fg = P.func })
	set("@method.call", { fg = P.func })
	set("@number.float", { fg = P.number })
	set("@string.special", { fg = P.string })
	set("@text", { fg = fg })
	set("@text.strong", { fg = fg, bold = true })
	set("@text.emphasis", { fg = fg, italic = true })
	set("@text.underline", { fg = fg, underline = true })
	set("@text.strike", { fg = fg, strikethrough = true })
	set("@text.title", { fg = P.accent })
	set("@text.literal", { fg = P.string })
	set("@text.quote", { fg = P.comment })
	set("@text.uri", { fg = P.accent, underline = true })
	set("@text.math", { fg = P.number })
	set("@text.environment", { fg = P.accent })
	set("@text.environment.name", { fg = P.func })
	set("@text.reference", { fg = P.accent })
	set("@text.note", { fg = P.accent })
	set("@text.warning", { fg = P.diag_yellow })
	set("@text.danger", { fg = P.diag_red })
	set("@text.diff.add", { fg = P.diag_green })
	set("@text.diff.delete", { fg = P.diag_red })
	set("@text.todo.checked", { fg = P.accent })
	set("@text.todo.unchecked", { fg = P.comment })
	set("@text.todo", { fg = P.bg, bg = P.string })
	set("@text.link", { fg = P.accent, underline = true })
	set("@text.link.url", { fg = P.accent, underline = true })
	set("@text.link.label", { fg = P.func })
	set("@markup.heading", { fg = P.accent })
	set("@markup.strong", { fg = fg, bold = true })
	set("@markup.emphasis", { fg = fg, italic = true })
	set("@markup.underline", { fg = fg, underline = true })
	set("@markup.strikethrough", { fg = fg, strikethrough = true })
	set("@markup.link", { fg = P.accent, underline = true })
	set("@markup.link.url", { fg = P.accent, underline = true })
	set("@markup.link.label", { fg = P.func })
	set("@markup.list", { fg = P.operator })
	set("@markup.list.checked", { fg = P.accent })
	set("@markup.list.unchecked", { fg = P.comment })
	set("@markup.raw", { fg = P.string })
	set("@markup.quote", { fg = P.comment })
	set("@markup.heading.1", { fg = P.accent, bold = true })
	set("@markup.heading.2", { fg = P.accent, bold = true })
	set("@markup.heading.3", { fg = P.accent, bold = true })
	set("@markup.heading.4", { fg = P.accent, bold = true })
	set("@markup.heading.5", { fg = P.accent, bold = true })
	set("@markup.heading.6", { fg = P.accent, bold = true })
	set("@annotation", { fg = P.keyword })
	set("@attribute.builtin", { fg = P.accent })
	set("@keyword.storage", { fg = P.keyword })
	set("@keyword.directive", { fg = P.keyword })

	-- LSP
	set("LspReferenceText", { fg = P.accent, bg = P.visual })
	set("LspReferenceWrite", { fg = P.accent, bg = P.visual })
	set("LspReferenceRead", { fg = P.accent, bg = P.visual })
	set("LspCodeLens", { fg = P.comment })
	set("LspCodeLensSeparator", { fg = P.comment })
	set("LspSignatureActiveParameter", { fg = P.accent })
	set("LspInlayHint", { fg = P.comment, bg = P.alt_bg })
	set("DiagnosticDefaultError", { fg = P.diag_red })
	set("DiagnosticDefaultWarn", { fg = P.diag_yellow })
	set("DiagnosticDefaultInfo", { fg = P.diag_blue })
	set("DiagnosticDefaultHint", { fg = P.accent })
	set("DiagnosticUnderlineError", { undercurl = true, sp = P.diag_red })
	set("DiagnosticUnderlineWarn", { undercurl = true, sp = P.diag_yellow })
	set("DiagnosticUnderlineInfo", { undercurl = true, sp = P.diag_blue })
	set("DiagnosticUnderlineHint", { undercurl = true, sp = P.accent })
	set("DiagnosticVirtualTextError", { fg = P.diag_red })
	set("DiagnosticVirtualTextWarn", { fg = P.diag_yellow })
	set("DiagnosticVirtualTextInfo", { fg = P.diag_blue })
	set("DiagnosticVirtualTextHint", { fg = P.accent })
	set("DiagnosticSignError", { fg = P.diag_red })
	set("DiagnosticSignWarn", { fg = P.diag_yellow })
	set("DiagnosticSignInfo", { fg = P.diag_blue })
	set("DiagnosticSignHint", { fg = P.accent })
	set("DiagnosticFloatingError", { fg = P.diag_red })
	set("DiagnosticFloatingWarn", { fg = P.diag_yellow })
	set("DiagnosticFloatingInfo", { fg = P.diag_blue })
	set("DiagnosticFloatingHint", { fg = P.accent })

	-- Git
	set("diffAdded", { fg = P.diag_green })
	set("diffRemoved", { fg = P.diag_red })
	set("diffChanged", { fg = P.accent })
	set("diffOldFile", { fg = P.comment })
	set("diffNewFile", { fg = P.accent })
	set("diffFile", { fg = P.accent })
	set("diffIndexLine", { fg = P.comment })

	-- Plugins
	set("TelescopeNormal", { fg = fg, bg = P.alt_bg })
	set("TelescopePromptBorder", { fg = P.accent })
	set("TelescopeResultsBorder", { fg = P.comment })
	set("TelescopePreviewBorder", { fg = P.comment })
	set("TelescopeSelection", { fg = P.fg, bg = P.visual })
	set("NvimTreeNormal", { fg = fg, bg = bg })
	set("NvimTreeIndentMarker", { fg = P.comment })
	set("NvimTreeGitDirty", { fg = P.diag_yellow })
	set("NvimTreeGitStaged", { fg = P.accent })
	set("NvimTreeGitDeleted", { fg = P.diag_red })
	set("BufferLineBackground", { bg = P.alt_bg })
	set("BufferLineBufferSelected", { fg = P.accent, bg = bg })
	set("BufferLineBufferVisible", { fg = P.comment })
	set("BufferLineSeparatorSelected", { fg = P.alt_bg })
	set("CmpItemAbbr", { fg = fg })
	set("CmpItemAbbrDeprecated", { fg = P.comment })
	set("CmpItemAbbrMatch", { fg = P.accent })
	set("CmpItemKindFunction", { fg = P.func })
	set("CmpItemKindMethod", { fg = P.func })
	set("CmpItemKindKeyword", { fg = P.keyword })
	set("CmpItemKindVariable", { fg = fg })
	set("CmpItemKindConstant", { fg = P.constant })
	set("CmpItemKindClass", { fg = P.type })
	set("CmpItemKindStruct", { fg = P.type })
	set("CmpItemKindInterface", { fg = P.type })
	set("CmpItemKindModule", { fg = P.type })
	set("CmpItemKindProperty", { fg = P.property })
	set("CmpItemKindEnum", { fg = P.constant })
	set("CmpItemKindEnumMember", { fg = P.constant })
	set("CmpItemKindTypeParameter", { fg = P.type })
	set("CmpItemKindText", { fg = fg })
	set("CmpItemKindSnippet", { fg = P.string })
	set("CmpItemKindColor", { fg = P.string })
	set("CmpItemKindFile", { fg = P.func })
	set("CmpItemKindReference", { fg = P.func })
	set("CmpItemKindFolder", { fg = P.func })
	set("CmpItemKindUnit", { fg = P.constant })
	set("CmpItemKindValue", { fg = P.constant })
	set("CmpItemKindOperator", { fg = P.operator })

	-- Lualine
	set("LualineNormal", { fg = fg, bg = P.bg })
	set("LualineInsert", { fg = P.bg, bg = P.accent })
	set("LualineVisual", { fg = P.bg, bg = P.comment })
	set("LualineReplace", { fg = P.bg, bg = P.string })
	set("LualineCommand", { fg = P.bg, bg = P.keyword })

	-- GitSigns
	set("GitSignsAdd", { fg = P.diag_green })
	set("GitSignsChange", { fg = P.accent })
	set("GitSignsDelete", { fg = P.diag_red })
	set("GitSignsAddLn", { fg = P.diag_green })
	set("GitSignsChangeLn", { fg = P.accent })
	set("GitSignsDeleteLn", { fg = P.diag_red })

	-- Terminal colors
	vim.g.terminal_color_0 = P.alt_bg
	vim.g.terminal_color_1 = P.diag_red
	vim.g.terminal_color_2 = P.property
	vim.g.terminal_color_3 = P.func
	vim.g.terminal_color_4 = P.constant
	vim.g.terminal_color_5 = P.keyword
	vim.g.terminal_color_6 = P.string
	vim.g.terminal_color_7 = P.fg
	vim.g.terminal_color_8 = P.comment
	vim.g.terminal_color_9 = P.diag_red
	vim.g.terminal_color_10 = P.property
	vim.g.terminal_color_11 = P.func
	vim.g.terminal_color_12 = P.constant
	vim.g.terminal_color_13 = P.keyword
	vim.g.terminal_color_14 = P.string
	vim.g.terminal_color_15 = P.fg
end

return M
